### ISSUE TITLE
Search Not Working

### ISSUE THREAD

**Issue by norrisrahman** [Overd0se9/cpp-crud-library#1]
hello, im trying compile your code but search functions is not working. can you explain it ?

**Comment by EG-SN1PER** [comment]
> hello, im trying compile your code but search functions is not working. can you explain it ?

I am sorry , but actually I am in the military service   ، I will check it when I go back home

**Comment by Overd0se9** [comment]
> hello, im trying compile your code but search functions is not working. can you explain it ?

I am sorry , but actually I am in the military service   ، I will check it when I go back home
